### ISSUE TITLE
Upgrade to thumbor 7

### ISSUE THREAD

**Issue by heynemann** [scorphus/thumbor-wand-engine#9]
Hey @scorphus! This is some amazing work! What do you say we migrate this to thumbor 7 and python 3?

Anyway great job! I'm adding this to awesome thumbor.

**Comment by scorphus** [comment]
Hey, @heynemann!

Awesome stuff what you've been putting together for Thumbor recently! :muscle: Thank you for that and also for adding the Wand engine to awesome thumbor! Wunderbar! :tada: 

The Wand engine does not require any specific version of thumbor. As long as the user has thumbor installed, they should be good. It also supports both versions 6 and 7 of ImageMagick ;-) 

It already works on (and requires) Python 3.6 or newer! YAY! But I'll take the chance to update the classifiers, though, as they list only 3.6, 3.7 and 3.8.
